apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sleeperpy
  name: sleeperpy
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: sleeperpy
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: sleeperpy
    spec:
      containers:
        - image: wbollock/sleeperpy:latest
          name: sleeperpy
          #command: [ "/bin/bash", "-c", "--" ]
          #args: [ "while true; do sleep 30; done;" ]
        - image: mongo:latest
          name: mongodb
        
status: {}
